#cloud:
#  aws:
#    s3:
#      bucket: "project-hunmin"
#    region:
#      static: "ap-northeast-2"
#    credentials:
#      access-key: ${{ secrets.AWS_ACCESS_KEY }}
#      secret-key: ${{ secrets.AWS_SECRET_KEY }}
#
#logging:
#  level:
#    com.amazonaws: DEBUG
#    software.amazon.awssdk: DEBUG
#    com.hunmin: DEBUG