name: hunmin kotlin dev CI/CD

on:
  push:
    branches:
      - 'feature/#119-feat-깃허브-액션-설정'  # 특정 브랜치에서 push 발생시 실행 테스트 후 삭제해야함.
  pull_request:
    types: [closed] # PR이 닫힐때 실행
  workflow_dispatch: # 수동 실행도 가능하도록

jobs:
  build:
    runs-on: ubuntu-latest # OS환경
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/feature/#119-feat-깃허브-액션-설정') || 
      (github.event_name == 'pull_request' && 
       github.event.pull_request.merged == true && 
       github.event.pull_request.base.ref == 'develop')

    #if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop' # develop 브랜치

    steps:
      - name: Checkout
        uses: actions/checkout@v3 # 코드 체크아웃
        with:
          fetch-depth: 0  # 전체 히스토리를 가져옴

      - name: Set up JDK 17 for Kotlin
        uses: actions/setup-java@v3
        with:
          java-version: 17 # 자바 설치
          distribution: 'adopt'


#      - name: Set up Node.js for React
#        uses: actions/setup-node@v3
#        with:
#          node-version: '20' # Node.js 설치

#      - name: Install React dependencies
#        run: npm install
#        working-directory: ./hunmin-front # React 애플리케이션 디렉토리 설정
#        shell: bash

#      - name: Build React app
#        run: npm run build
#        working-directory: ./hunmin-front # React 빌드 실행
#        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash # 권한 부여

      - name: Build with Gradle
        run: ./gradlew clean build -x test
        shell: bash # Kotlin 빌드 시작

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00" # 빌드 시점의 시간 확보

      - name: Show Current Time
        run: echo "CurrentTime=${{ steps.current-time.outputs.formattedTime }}"
        shell: bash # 확보한 시간 보여주기

      - name: Generate deployment package
        run: |
          mkdir -p deploy
          cp build/libs/*.jar deploy/application.jar
          cp Procfile deploy/Procfile
          cp -r .ebextensions_dev deploy/.ebextensions
          cp -r .platform deploy/.platform
          cd deploy && zip -r deploy.zip .

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACTION_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_ACTION_SECRET_ACCESS_KEY }}
          application_name: kotlin-hunmin
          environment_name: Kotlin-hunmin-env
          version_label: github-action-${{ steps.current-time.outputs.formattedTime }}
          region: ap-northeast-2
          deployment_package: deploy/deploy.zip
          wait_for_deployment: false